site_name: Mimi.jl
repo_url: https://github.com/anthofflab/Mimi.jl
site_description: Integrated Assessment Modeling Framework
site_author: anthofflab

theme: material

extra:
  palette:
    primary: 'indigo'
    accent: 'blue'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Installation Guide: installation.md
  - Tutorial: tutorial.md
  - FAQ: faq.md
  - Reference: reference.md
